[project]
name = "build-llm-from-scratch"
version = "0.1.0"
description = "My working notes from Build an LLM from Scratch by Sebastian Rachka"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.0",
    "matplotlib>=3.7.1",
    "numpy>=1.26,<2.1",
    "pandas>=2.2.1",
    "psutil>=5.9.5",
    "tensorflow>=2.18.0",
    "tiktoken>=0.5.1",
    "torch>=2.3.0",
    "torchvision>=0.21.0",
    "tqdm>=4.66.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
